In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv('employees.csv')

In [5]:
dataframe.shape

(6, 4)

In [6]:
dataframe.head(10)

      Name   Department  Salary  Experience
0    Alice  Engineering   70000           5
1      Bob           HR   50000           2
2  Charlie  Engineering   75000           6
3    David    Marketing   60000           3
4      Eve  Engineering   80000           8
5    Frank           HR   45000           1

In [17]:
tdf = dataframe[dataframe['Department'] == 'Engineering']
tdf.sort_values(by='Salary', ascending=True)
tdf

      Name   Department  Salary  Experience
0    Alice  Engineering   70000           5
2  Charlie  Engineering   75000           6
4      Eve  Engineering   80000           8

###  Pandas DataFrame Advanced Manipulation
**Question:** Write a function `top_n_earners_in_dept` that reads the file into a pandas DataFrame and returns a DataFrame of the top `n` earners in a specific department, sorted by salary in descending order.

In [27]:
def top_n_earners_in_dept(file_path, department, size):
    # Read the file into a DataFrame
    df = pd.read_csv(file_path)
    
    #Filter the DataFrame by the specific department
    filtered_df = df[df['Department'] == department]
    
    #Sort the DataFrame by salary in descending order
    sorted_df = filtered_df.sort_values(by='Salary', ascending=False)
    
    #Return the top n earners
    return sorted_df.head(size)

In [29]:
print(top_n_earners_in_dept('employees.csv', 'Engineering', 2))  # Expected: DataFrame with Eve and Charlie
print()
print(top_n_earners_in_dept('employees.csv', 'HR', 2))  # Expected: DataFrame with Bob and Frank
print()
print(top_n_earners_in_dept('employees.csv', 'Marketing', 1))  # Expected: DataFrame with David

      Name   Department  Salary  Experience
4      Eve  Engineering   80000           8
2  Charlie  Engineering   75000           6

    Name Department  Salary  Experience
1    Bob         HR   50000           2
5  Frank         HR   45000           1

    Name Department  Salary  Experience
3  David  Marketing   60000           3

### String Processing with Advanced Regular Expressions
**Question:** Write a function `extract_domain_names` that takes a list of URLs and returns the domain names. Extract only the main domai

In [34]:

import re

# List of common second-level domains (SLDs) like 'co.uk', 'com.au'
SLD_EXCEPTIONS = {'co.uk', 'org.uk', 'gov.uk', 'ac.uk', 'com.au', 'net.au'}

def extract_domain_names(urls):
    main_domains = []
    domain_pattern = r'https?://(?:www\.)?([^/]+)'

    for url in urls:
        # Extract domain using regex
        match = re.search(domain_pattern, url)
        if match:
            domain = match.group(1)
            # Split the domain into parts
            parts = domain.split('.')
            
            # Special handling for common second-level domains
            if len(parts) > 2 and '.'.join(parts[-2:]) in SLD_EXCEPTIONS:
                # If domain has a special second-level domain like 'co.uk', take the last three parts
                main_domain = '.'.join(parts[-3:])
            else:
                # Otherwise, take the last two parts as the main domain
                main_domain = '.'.join(parts[-2:])
            
            # Add the main domain to the result list
            main_domains.append(main_domain)
    
    return main_domains

In [35]:
print(extract_domain_names(['https://www.sub.example.com/path?query=1', 'http://another.sub.domain.co.uk/path', 'https://example.org']))  # Expected: ['example.com', 'domain.co.uk', 'example.org']
print(extract_domain_names(['https://sub.google.com', 'http://sub.domain.co.uk', 'https://example.com']))  # Expected: ['google.com', 'domain.co.uk', 'example.com']

['example.com', 'domain.co.uk', 'example.org']
['google.com', 'domain.co.uk', 'example.com']